name: locaze
services:
  server:
    image: manh001/locaze:latest
    env_file:
      - .env
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=locaze
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=locaze@123
